<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Notifications extends CI_Controller {

    function __construct() {
        parent::__construct();
        chek_session();
    }

    public function test()
    {
        $user = $this->ion_auth->users('admin')->result();
        // echo $user->email;
        echo json_encode($user);
  
    }

    public function fetch() {
        header('Content-Type: application/json');
        // if ($this->input->post("view")) {
            if ($this->input->post("view") != '') {
                $this->NotificationModels->update($this->session->userdata('user_id'));
            }
            $DataNotif = $this->NotificationModels->getAll();
            $count = $this->NotificationModels->countNotif();
            $data = array(
                'notification'   => $DataNotif,
                'unseen_notification' => $count
            );
            echo json_encode($data);

        // } else {
        //     echo "Gagal mengambil notif";
        // }
    }

    public function read($id) {
    }
    
    public function create() {
    }

    public function create_action() {
    }

    public function update($id) {
        $this->NotificationModels->update($id);
    }

    public function update_action() {
    }

    public function delete($id) {
    }

    public function _rules() {
    }

    public function excel() {
    }

}

/* End of file Pelanggan.php */
/* Location: ./application/controllers/Pelanggan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:09:25 */
/* http://harviacode.com */